skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
my_counter = "3gW4EMz31zs6HMxyoCWUb5mxXeLj4V3Ur2H41VvPWPMM"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
